name: Build and deploy Python app to Azure Web App - avo-csv-converter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x "venv/*" \
               ".venv/*" \
               ".git/*" \
               ".github/*" \
               "__pycache__/*" \
               "*.pyc"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C28780C580504340B5E9DA04935A3DEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2774397197DD4E6EBDE18F8D74837CF3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A1D72ED5B57D4ACAAAABAC0E94285AFE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "avo-csv-converter"
          slot-name: "Production"
          package: release.zip
